version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_lVx1z7WCnbkm@ep-shy-mud-a1tt0j2z-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
      - SECRET_KEY=your-secret-key-here
      - API_V1_STR=/api/v1
      - PROJECT_NAME=FarmSync API
      - VERSION=1.0.0
    networks:
      - farmsync-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  farmsync-network:
    driver: bridge 